services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: gunicorn app.api.v1.main:app --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PORT
        value: 10000
