services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.api.v1.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
